### ISSUE TITLE
Bug: Library is not properly supported in nuxt app

### ISSUE THREAD

**Issue by ashokvaishnav708** [geprog/former#12]
The updated version 0.0.2 does work pretty fine in the Playground. But does not support in nuxt app. It does show a UI, but nothing happens when clicking "+" button. Also the below error appears:

`[Vue warn]: Failed to resolve component: FormKit
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.`

**Comment by lukashass** [comment]
Closed by 157b171dc65acfb90f5e975045142401858fdcf1
