### ISSUE TITLE
Allow to pass custom components

### ISSUE THREAD

**Issue by anbraten** [geprog/former#16]
It would be nice to allow to replace some internal components in case a user wants a custom design.
Components to be allowed to adjusted would be:
- `FormFieldTypeSelector.vue`
- `FormKitEdit.vue`
- `FormFieldOptions.vue`
- `FormContent.vue`

**Comment by mariusheine** [comment]
@anbraten This should already be possible by formkit theming and overriding formkit components since we are only using formkit. Or am I missing something?

**Comment by mariusheine** [comment]
Obsolete as former is now headless
