### ISSUE TITLE
Introduce autocalculation element

### ISSUE THREAD

**Issue by ashokvaishnav708** [geprog/former#58]
The element must evaluate the formula based on other nodes input values. The auto calculation element must have following characteristics:

- a technical name for referencing and persisting
-  a label
- no default value
- show if condition
- calculation formula
- a description for the formula
- validation

**Comment by mariusheine** [comment]
@ashokvaishnav708 This feature has nothing to do here. former is headless which means every required component must be implemented in the actual app where former is integrated.
