### ISSUE TITLE
Add basic input components

### ISSUE THREAD

**Issue by ashokvaishnav708** [geprog/former#7]
- [x] text (https://formkit.com/inputs/text)
- [ ] select (https://formkit.com/inputs/select)
- [ ] checkbox (https://formkit.com/inputs/checkbox)
- [ ] radio button (https://formkit.com/inputs/radio)
- [ ] text area (https://formkit.com/inputs/textarea)
- [x] number field (https://formkit.com/inputs/number)

**Comment by mariusheine** [comment]
Obsolete as former is now headless
